enabled: true
production-mode: false
favicon:
  user/themes/future2021/images/logo/Grav_logo.png:
    name: Grav_logo.png
    type: image/png
    size: 15355
    path: user/themes/future2021/images/logo/Grav_logo.png
blog_page: /blog
slogan: 'RESPONSIVE SITE TEMPLATE BY HTML5 UP PORTED TO GRAV'
custom_logo:
  user/themes/future2021/images/logo/Grav_logo.png:
    name: Grav_logo.png
    type: image/png
    size: 15355
    path: user/themes/future2021/images/logo/Grav_logo.png
custom_logo_mobile: {  }
footer:
  title: ABOUT
  description: 'Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod amet placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at phasellus sed ultricies.'
  copyright_text: 'DESIGN: <a href="https://html5up.net/" target="_blank">HTML5 UP</a>. IMAGES by <a href="https://unsplash.com/es/@davealmine" target="_blank">Dawid Zawiła</a>.'
  button_url: about
  button_text: 'Show more'
social:
  -
    name: Twitter
    url: 'https://www.twitter.com'
    icon: 'fa fa-twitter'
  -
    name: Facebook
    url: 'https://www.facebook.com'
    icon: 'fa fa-facebook'
  -
    name: Instagram
    url: 'https://www.instagram.com'
    icon: 'fa fa-instagram'
latestposts: true
miniposts_category: minipost
displaycustommenus:
  enabled: true
dropdown:
  enabled: true
custommenu:
  -
    text: Grav
    icon: arrow-circle-right
    url: 'https://getgrav.org'
    target: _blank
sidebar: true
custommenus:
  enabled: true
menu_langswitcher: false
menu_search: true
menu_login: true
enable_social: true
social_style: brands
miniposts: true
miniposts_number: 3
recent_posts_enabled: true
recent_posts_number: 5
