title: Generic Page
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        content:
          type: tab
          fields:
            header.options:
              type: columns
              ordering@: header.title
              fields:
                header.content:
                  type: column
                  fields:
                    header.subtitle:
                      type: text
                      style: vertical
                      label: FUTURE.ADMIN.ITEM.ITEM_SUBTITLE
                    header.primaryImage:
                      ordering@: header.subtitle
                      style: vertical
                      size: medium
                      type: pagemediaselect
                      label: FUTURE.ADMIN.DEFAULT.PRIMARY_IMAGE
                      preview_images: true
        options:
          fields:
            publishing:
              fields:
                header.show_sidebar:
                  type: toggle
                  toggleable: true
                  label: FUTURE.ADMIN.DEFAULT.SHOW_SIDEBAR
                  ordering@: -99
                  default: 0
                  highlight: 0
                  options:
                    1: PLUGIN_ADMIN.ENABLED
                    0: PLUGIN_ADMIN.DISABLED
                  validate:
                    type: bool
        advanced:
          fields:
            columns:
              fields:
                column1:
                   fields:
                     header.body_classes:
                       markdown: true
                       description: FUTURE.ADMIN.DEFAULT.BODY_CLASSES